services:
  - name: ss服务
    mode: ss
    localPort: 9089
    passWord: a
    encrypt: aes-128-gcm
    enable: false

  - name: 端口转发服务
    mode: forward
    serverHost: 127.0.0.1
    serverPort: 9089
    localPort: 9090
    enable: false

  - name: HTTP代理服务
    mode: http_proxy
    localPort: 9999
    userName: a
    passWord: a
    enable: true